apiVersion: apps/v1
kind: Deployment
metadata:
  name: laraks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laraks
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: laraks
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: laraks
        image: {{CONTAINERREGISTRY}}/{{CONTAINERTAG}}
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: APP_KEY
          value: "{{APP_KEY}}"
